# Write your MySQL query statement below

-- GETS PRODUCT_IDS AND PRICE FOR THE PRODUCTS CHANGE DATE <= "2019-08-16" WITH RK = 1
SELECT product_id, new_price price
FROM

-- SUBQUERY - RANKS THE PRODUCTS WITHIN PRODUCT_ID BY ORDER - CHANGE_DATE DESC (GREATEST TO SMALLEST)
(
    SELECT *, RANK() OVER( PARTITION BY PRODUCT_ID ORDER BY CHANGE_DATE DESC) AS RK
    FROM PRODUCTS
    WHERE change_date <= "2019-08-16"
) T1
WHERE RK = 1

UNION

-- RETURNS THE PRODUCT THATS PRICE DIDN'T CHANGE BEFORE "2019-08-16" AND DEFAULT VALUE AS 10.

SELECT product_id, 10 price
FROM Products 
WHERE CHANGE_DATE >=  "2019-08-16" 
AND product_id NOT IN (
    SELECT PRODUCT_ID
    FROM PRODUCTS
    WHERE change_date <= "2019-08-16"
)
;

-- USED UNION TO GOIN BOTH THE TABLES/QUERY TO GET THE DESIRED OUTPUT.
